import React from 'react';
import { BookOpen, Moon, ScrollText, Sun, SunMedium, Sunrise, Sunset } from "lucide-react";

export const prayerTimes = [
    { name: 'Fajr', time: '04:30', icon: React.createElement(Sunrise, { className: "w-5 h-5" }) },
    { name: 'Dhuhr', time: '12:45', icon: React.createElement(Sun, { className: "w-5 h-5" }) },
    { name: 'Asr', time: '16:15', icon: React.createElement(SunMedium, { className: "w-5 h-5" }) },
    { name: 'Maghrib', time: '19:00', icon: React.createElement(Sunset, { className: "w-5 h-5" }) },
    { name: 'Isha', time: '20:30', icon: React.createElement(Moon, { className: "w-5 h-5" }) },
];

export const qiblaDirection = {
    degrees: 128,
    direction: 'SE'
};

export const surahs = [
    { number: 1, name: 'Al-Fatiha', nameArabic: 'الفاتحة', versesCount: 7, revelationPlace: 'Mecca' },
    { number: 2, name: 'Al-Baqarah', nameArabic: 'البقرة', versesCount: 286, revelationPlace: 'Medina' },
    { number: 3, name: 'Aal-E-Imran', nameArabic: 'آل عمران', versesCount: 200, revelationPlace: 'Medina' },
    { number: 4, name: 'An-Nisa', nameArabic: 'النساء', versesCount: 176, revelationPlace: 'Medina' },
    { number: 5, name: 'Al-Maidah', nameArabic: 'المائدة', versesCount: 120, revelationPlace: 'Medina' },
    { number: 6, name: 'Al-Anam', nameArabic: 'الأنعام', versesCount: 165, revelationPlace: 'Mecca' },
    { number: 7, name: 'Al-Araf', nameArabic: 'الأعراف', versesCount: 206, revelationPlace: 'Mecca' },
    { number: 8, name: 'Al-Anfal', nameArabic: 'الأنفال', versesCount: 75, revelationPlace: 'Medina' },
    { number: 9, name: 'At-Tawbah', nameArabic: 'التوبة', versesCount: 129, revelationPlace: 'Medina' },
    { number: 10, name: 'Yunus', nameArabic: 'يونس', versesCount: 109, revelationPlace: 'Mecca' },
    { number: 11, name: 'Hud', nameArabic: 'هود', versesCount: 123, revelationPlace: 'Mecca' },
    { number: 12, name: 'Yusuf', nameArabic: 'يوسف', versesCount: 111, revelationPlace: 'Mecca' },
    { number: 13, name: 'Ar-Rad', nameArabic: 'الرعد', versesCount: 43, revelationPlace: 'Medina' },
    { number: 14, name: 'Ibrahim', nameArabic: 'ابراهيم', versesCount: 52, revelationPlace: 'Mecca' },
    { number: 15, name: 'Al-Hijr', nameArabic: 'الحجر', versesCount: 99, revelationPlace: 'Mecca' },
    { number: 16, name: 'An-Nahl', nameArabic: 'النحل', versesCount: 128, revelationPlace: 'Mecca' },
    { number: 17, name: 'Al-Isra', nameArabic: 'الإسراء', versesCount: 111, revelationPlace: 'Mecca' },
    { number: 18, name: 'Al-Kahf', nameArabic: 'الكهف', versesCount: 110, revelationPlace: 'Mecca' },
    { number: 19, name: 'Maryam', nameArabic: 'مريم', versesCount: 98, revelationPlace: 'Mecca' },
    { number: 20, name: 'Taha', nameArabic: 'طه', versesCount: 135, revelationPlace: 'Mecca' },
    { number: 21, name: 'Al-Anbiya', nameArabic: 'الأنبياء', versesCount: 112, revelationPlace: 'Mecca' },
    { number: 22, name: 'Al-Hajj', nameArabic: 'الحج', versesCount: 78, revelationPlace: 'Medina' },
    { number: 23, name: 'Al-Muminun', nameArabic: 'المؤمنون', versesCount: 118, revelationPlace: 'Mecca' },
    { number: 24, name: 'An-Nur', nameArabic: 'النور', versesCount: 64, revelationPlace: 'Medina' },
    { number: 25, name: 'Al-Furqan', nameArabic: 'الفرقان', versesCount: 77, revelationPlace: 'Mecca' },
    { number: 26, name: 'Ash-Shuara', nameArabic: 'الشعراء', versesCount: 227, revelationPlace: 'Mecca' },
    { number: 27, name: 'An-Naml', nameArabic: 'النمل', versesCount: 93, revelationPlace: 'Mecca' },
    { number: 28, name: 'Al-Qasas', nameArabic: 'القصص', versesCount: 88, revelationPlace: 'Mecca' },
    { number: 29, name: 'Al-Ankabut', nameArabic: 'العنكبوت', versesCount: 69, revelationPlace: 'Mecca' },
    { number: 30, name: 'Ar-Rum', nameArabic: 'الروم', versesCount: 60, revelationPlace: 'Mecca' },
    { number: 31, name: 'Luqman', nameArabic: 'لقمان', versesCount: 34, revelationPlace: 'Mecca' },
    { number: 32, name: 'As-Sajdah', nameArabic: 'السجدة', versesCount: 30, revelationPlace: 'Mecca' },
    { number: 33, name: 'Al-Ahzab', nameArabic: 'الأحزاب', versesCount: 73, revelationPlace: 'Medina' },
    { number: 34, name: 'Saba', nameArabic: 'سبإ', versesCount: 54, revelationPlace: 'Mecca' },
    { number: 35, name: 'Fatir', nameArabic: 'فاطر', versesCount: 45, revelationPlace: 'Mecca' },
    { number: 36, name: 'Ya-Sin', nameArabic: 'يس', versesCount: 83, revelationPlace: 'Mecca' },
    { number: 37, name: 'As-Saffat', nameArabic: 'الصافات', versesCount: 182, revelationPlace: 'Mecca' },
    { number: 38, name: 'Sad', nameArabic: 'ص', versesCount: 88, revelationPlace: 'Mecca' },
    { number: 39, name: 'Az-Zumar', nameArabic: 'الزمر', versesCount: 75, revelationPlace: 'Mecca' },
    { number: 40, name: 'Ghafir', nameArabic: 'غافر', versesCount: 85, revelationPlace: 'Mecca' },
    { number: 41, name: 'Fussilat', nameArabic: 'فصلت', versesCount: 54, revelationPlace: 'Mecca' },
    { number: 42, name: 'Ash-Shuraa', nameArabic: 'الشورى', versesCount: 53, revelationPlace: 'Mecca' },
    { number: 43, name: 'Az-Zukhruf', nameArabic: 'الزخرف', versesCount: 89, revelationPlace: 'Mecca' },
    { number: 44, name: 'Ad-Dukhan', nameArabic: 'الدخان', versesCount: 59, revelationPlace: 'Mecca' },
    { number: 45, name: 'Al-Jathiyah', nameArabic: 'الجاثية', versesCount: 37, revelationPlace: 'Mecca' },
    { number: 46, name: 'Al-Ahqaf', nameArabic: 'الأحقاف', versesCount: 35, revelationPlace: 'Mecca' },
    { number: 47, name: 'Muhammad', nameArabic: 'محمد', versesCount: 38, revelationPlace: 'Medina' },
    { number: 48, name: 'Al-Fath', nameArabic: 'الفتح', versesCount: 29, revelationPlace: 'Medina' },
    { number: 49, name: 'Al-Hujurat', nameArabic: 'الحجرات', versesCount: 18, revelationPlace: 'Medina' },
    { number: 50, name: 'Qaf', nameArabic: 'ق', versesCount: 45, revelationPlace: 'Mecca' },
    { number: 51, name: 'Adh-Dhariyat', nameArabic: 'الذاريات', versesCount: 60, revelationPlace: 'Mecca' },
    { number: 52, name: 'At-Tur', nameArabic: 'الطور', versesCount: 49, revelationPlace: 'Mecca' },
    { number: 53, name: 'An-Najm', nameArabic: 'النجم', versesCount: 62, revelationPlace: 'Mecca' },
    { number: 54, name: 'Al-Qamar', nameArabic: 'القمر', versesCount: 55, revelationPlace: 'Mecca' },
    { number: 55, name: 'Ar-Rahman', nameArabic: 'الرحمن', versesCount: 78, revelationPlace: 'Medina' },
    { number: 56, name: 'Al-Waqiah', nameArabic: 'الواقعة', versesCount: 96, revelationPlace: 'Mecca' },
    { number: 57, name: 'Al-Hadid', nameArabic: 'الحديد', versesCount: 29, revelationPlace: 'Medina' },
    { number: 58, name: 'Al-Mujadila', nameArabic: 'المجادلة', versesCount: 22, revelationPlace: 'Medina' },
    { number: 59, name: 'Al-Hashr', nameArabic: 'الحشر', versesCount: 24, revelationPlace: 'Medina' },
    { number: 60, name: 'Al-Mumtahanah', nameArabic: 'الممتحنة', versesCount: 13, revelationPlace: 'Medina' },
    { number: 61, name: 'As-Saf', nameArabic: 'الصف', versesCount: 14, revelationPlace: 'Medina' },
    { number: 62, name: 'Al-Jumuah', nameArabic: 'الجمعة', versesCount: 11, revelationPlace: 'Medina' },
    { number: 63, name: 'Al-Munafiqun', nameArabic: 'المنافقون', versesCount: 11, revelationPlace: 'Medina' },
    { number: 64, name: 'At-Taghabun', nameArabic: 'التغابن', versesCount: 18, revelationPlace: 'Medina' },
    { number: 65, name: 'At-Talaq', nameArabic: 'الطلاق', versesCount: 12, revelationPlace: 'Medina' },
    { number: 66, name: 'At-Tahrim', nameArabic: 'التحريم', versesCount: 12, revelationPlace: 'Medina' },
    { number: 67, name: 'Al-Mulk', nameArabic: 'الملك', versesCount: 30, revelationPlace: 'Mecca' },
    { number: 68, name: 'Al-Qalam', nameArabic: 'القلم', versesCount: 52, revelationPlace: 'Mecca' },
    { number: 69, name: 'Al-Haqqah', nameArabic: 'الحاقة', versesCount: 52, revelationPlace: 'Mecca' },
    { number: 70, name: 'Al-Maarij', nameArabic: 'المعارج', versesCount: 44, revelationPlace: 'Mecca' },
    { number: 71, name: 'Nuh', nameArabic: 'نوح', versesCount: 28, revelationPlace: 'Mecca' },
    { number: 72, name: 'Al-Jinn', nameArabic: 'الجن', versesCount: 28, revelationPlace: 'Mecca' },
    { number: 73, name: 'Al-Muzzammil', nameArabic: 'المزمل', versesCount: 20, revelationPlace: 'Mecca' },
    { number: 74, name: 'Al-Muddaththir', nameArabic: 'المدثر', versesCount: 56, revelationPlace: 'Mecca' },
    { number: 75, name: 'Al-Qiyamah', nameArabic: 'القيامة', versesCount: 40, revelationPlace: 'Mecca' },
    { number: 76, name: 'Al-Insan', nameArabic: 'الانسان', versesCount: 31, revelationPlace: 'Medina' },
    { number: 77, name: 'Al-Mursalat', nameArabic: 'المرسلات', versesCount: 50, revelationPlace: 'Mecca' },
    { number: 78, name: 'An-Naba', nameArabic: 'النبإ', versesCount: 40, revelationPlace: 'Mecca' },
    { number: 79, name: 'An-Naziat', nameArabic: 'النازعات', versesCount: 46, revelationPlace: 'Mecca' },
    { number: 80, name: 'Abasa', nameArabic: 'عبس', versesCount: 42, revelationPlace: 'Mecca' },
    { number: 81, name: 'At-Takwir', nameArabic: 'التكوير', versesCount: 29, revelationPlace: 'Mecca' },
    { number: 82, name: 'Al-Infitar', nameArabic: 'الإنفطار', versesCount: 19, revelationPlace: 'Mecca' },
    { number: 83, name: 'Al-Mutaffifin', nameArabic: 'المطففين', versesCount: 36, revelationPlace: 'Mecca' },
    { number: 84, name: 'Al-Inshiqaq', nameArabic: 'الإنشقاق', versesCount: 25, revelationPlace: 'Mecca' },
    { number: 85, name: 'Al-Buruj', nameArabic: 'البروج', versesCount: 22, revelationPlace: 'Mecca' },
    { number: 86, name: 'At-Tariq', nameArabic: 'الطارق', versesCount: 17, revelationPlace: 'Mecca' },
    { number: 87, name: 'Al-Ala', nameArabic: 'الأعلى', versesCount: 19, revelationPlace: 'Mecca' },
    { number: 88, name: 'Al-Ghashiyah', nameArabic: 'الغاشية', versesCount: 26, revelationPlace: 'Mecca' },
    { number: 89, name: 'Al-Fajr', nameArabic: 'الفجر', versesCount: 30, revelationPlace: 'Mecca' },
    { number: 90, name: 'Al-Balad', nameArabic: 'البلد', versesCount: 20, revelationPlace: 'Mecca' },
    { number: 91, name: 'Ash-Shams', nameArabic: 'الشمس', versesCount: 15, revelationPlace: 'Mecca' },
    { number: 92, name: 'Al-Lail', nameArabic: 'الليل', versesCount: 21, revelationPlace: 'Mecca' },
    { number: 93, name: 'Ad-Duhaa', nameArabic: 'الضحى', versesCount: 11, revelationPlace: 'Mecca' },
    { number: 94, name: 'Ash-Sharh', nameArabic: 'الشرح', versesCount: 8, revelationPlace: 'Mecca' },
    { number: 95, name: 'At-Tin', nameArabic: 'التين', versesCount: 8, revelationPlace: 'Mecca' },
    { number: 96, name: 'Al-Alaq', nameArabic: 'العلق', versesCount: 19, revelationPlace: 'Mecca' },
    { number: 97, name: 'Al-Qadr', nameArabic: 'القدر', versesCount: 5, revelationPlace: 'Mecca' },
    { number: 98, name: 'Al-Bayyinah', nameArabic: 'البينة', versesCount: 8, revelationPlace: 'Medina' },
    { number: 99, name: 'Az-Zalzalah', nameArabic: 'الزلزلة', versesCount: 8, revelationPlace: 'Medina' },
    { number: 100, name: 'Al-Adiyat', nameArabic: 'العاديات', versesCount: 11, revelationPlace: 'Mecca' },
    { number: 101, name: 'Al-Qariah', nameArabic: 'القارعة', versesCount: 11, revelationPlace: 'Mecca' },
    { number: 102, name: 'At-Takathur', nameArabic: 'التكاثر', versesCount: 8, revelationPlace: 'Mecca' },
    { number: 103, name: 'Al-Asr', nameArabic: 'العصر', versesCount: 3, revelationPlace: 'Mecca' },
    { number: 104, name: 'Al-Humazah', nameArabic: 'الهمزة', versesCount: 9, revelationPlace: 'Mecca' },
    { number: 105, name: 'Al-Fil', nameArabic: 'الفيل', versesCount: 5, revelationPlace: 'Mecca' },
    { number: 106, name: 'Quraysh', nameArabic: 'قريش', versesCount: 4, revelationPlace: 'Mecca' },
    { number: 107, name: 'Al-Maun', nameArabic: 'الماعون', versesCount: 7, revelationPlace: 'Mecca' },
    { number: 108, name: 'Al-Kawthar', nameArabic: 'الكوثر', versesCount: 3, revelationPlace: 'Mecca' },
    { number: 109, name: 'Al-Kafirun', nameArabic: 'الكافرون', versesCount: 6, revelationPlace: 'Mecca' },
    { number: 110, name: 'An-Nasr', nameArabic: 'النصر', versesCount: 3, revelationPlace: 'Medina' },
    { number: 111, name: 'Al-Masad', nameArabic: 'المسد', versesCount: 5, revelationPlace: 'Mecca' },
    { number: 112, name: 'Al-Ikhlas', nameArabic: 'الإخلاص', versesCount: 4, revelationPlace: 'Mecca' },
    { number: 113, name: 'Al-Falaq', nameArabic: 'الفلق', versesCount: 5, revelationPlace: 'Mecca' },
    { number: 114, name: 'An-Nas', nameArabic: 'الناس', versesCount: 6, revelationPlace: 'Mecca' },
];

export const hadithCollections = [
    { name: 'Sahih al-Bukhari', total: 7563, icon: React.createElement(ScrollText) },
    { name: 'Sahih Muslim', total: 7563, icon: React.createElement(ScrollText) },
    { name: 'Jami` at-Tirmidhi', total: 3956, icon: React.createElement(ScrollText) },
    { name: 'Sunan an-Nasa\'i', total: 5758, icon: React.createElement(ScrollText) },
    { name: 'Sunan Abi Dawud', total: 5274, icon: React.createElement(ScrollText) },
    { name: 'Sunan Ibn Majah', total: 4341, icon: React.createElement(ScrollText) },
];

export const bookmarks = [
    { type: 'Verse', text: 'Al-Baqarah, 2:255 (Ayat al-Kursi)', icon: React.createElement(BookOpen, { className: "text-primary"}) },
    { type: 'Hadith', text: 'Bukhari, Hadith 1: On intentions', icon: React.createElement(ScrollText, { className: "text-primary"}) },
    { type: 'Verse', text: 'Ar-Rahman, 55:13', icon: React.createElement(BookOpen, { className: "text-primary"}) },
];

export const islamicEvents = [
    { date: '2024-06-16', name: 'Eid al-Adha', color: 'hsl(var(--accent))' },
    { date: '2024-07-07', name: 'Islamic New Year', color: 'hsl(var(--primary))' },
    { date: '2024-07-16', name: 'Day of Ashura', color: 'hsl(var(--secondary-foreground))' },
];
